"$schema" = "https://ubcode.useblocks.com/ubproject.schema.json"

server.index_on_save = true

[needs.fields.architect]
parse_variants = true
default = "unknown"
predicates = [
    ["var.arch == 'x86_64'", "x86_64"],
    ["var.arch == 'arm64'", "arm64"],
]

[needs]
variant_data_file = "variants1.json"
# variant_data.platform = "linux"
